
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: world-bike-map-tile-server-db
    environment:
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - PGDATA=/var/lib/postgresql/data
      - PGPASSWORD=${PGPASSWORD}
      - POSTGRES_DB=gis
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - THREADS=4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d gis"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        reservations:
          cpus: "4"
          memory: 2G
    ports:
      - "5432:5432"

  import:
    command: ["/bin/sh", "-c", "/import.sh"]
    build:
      context: .
      dockerfile: Dockerfile
    image: world-bike-map-tile-server
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - osm-data:/osm-data
      - osm-tiles:/var/lib/mod_tile
      - import-status:/import-status
    environment:
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - THREADS=8
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - DOWNLOAD_PBF=https://download.geofabrik.de/europe/isle-of-man-latest.osm.pbf
      - WGET_ARGS=--quiet
      - DOWNLOAD_POLY=
      - MAX_ZOOM=3
      - ALLOW_CORS=1
    deploy:
      resources:
        reservations:
          cpus: "12"
          memory: 2G

  server:
    command:
      [
        "/bin/sh",
        "-c",
        "/wait-for-file.sh /import-status/ready -t 0 && /server.sh",
      ]
    build:
      context: .
      dockerfile: Dockerfile
    image: world-bike-map-tile-server
    depends_on:
      db:
        condition: service_healthy
      import:
        condition: service_completed_successfully
    volumes:
      - osm-data:/osm-data
      - osm-tiles:/var/lib/mod_tile
      - import-status:/import-status
    environment:
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - THREADS=8
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - DOWNLOAD_PBF=https://download.geofabrik.de/europe/isle-of-man-latest.osm.pbf
      - WGET_ARGS=--quiet
      - DOWNLOAD_POLY=
      - MAX_ZOOM=15
      - ALLOW_CORS=1
    deploy:
      resources:
        reservations:
          cpus: "12"
          memory: 2G
    ports:
      - "8080:80"

volumes:
  osm-tiles:
  osm-data:
  import-status:
